### ISSUE TITLE
 zone-id is required

### ISSUE THREAD

**Issue by Hydrock** [nar3k/yc-public-tasks#25]
При прохождении этапа **Создание виртуальной машины на базе Container Optimized Image** и выполнения команды на создание ВМ - возникает ошибка ERROR: zone-id is required

**Comment by Hydrock** [comment]
После того как указал --zone="ru-central1-c"

ERROR: there are more than one subnets in zone 'ru-central1-c' in folder with id 'b1g3ncvg2h4ghmfjdm8a'.
Please choose subnet using --network-interface flag

**Comment by Hydrock** [comment]
делаю
 yc compute instance create-with-container --help | grep network-interface
получаю

If true, one-to-one NAT public IP will be created for the default network interface. Cannot be passed together with --network-interface
      --network-interface PROPERTY=VALUE[,PROPERTY=VALUE...]

а какие есть PROPERTY и VALUE не совсем понятно

**Comment by intr13** [comment]
Добавил предупреждение при создании без зоны в рецепт https://github.com/nar3k/yc-public-tasks/blob/master/container-registry/01/README.md

> Если вы не указали default compute zone при вызове yc init, то команда выше будет завершаться с требованием указать зону. Можно явно указать зону в которой должна быть создана виртуальная машина. Для этого надо добавить параметр --zone=ru-central1-c в команду выше. В указанном примере ожидается, что у вас существует сеть и подсеть в зоне ru-central1-c.

А про PROPERTY и VALUE можно прочитать так

> $ yc compute instance create-with-container --help | grep "network-interface PROPERTY" -A 22

**Comment by Hydrock** [comment]
спасибо
